#!/usr/bin/env node
/**
 * codegen-cli.js — Generates src/lib/generated/cli-options.js from parameter-schema-v2.json
 *
 * The generated file exports:
 * - cliOptions: array of {flag, description, choices, hidden, repeatable, defaultValue} for Commander
 * - helpGroups: mapping of flag → help section name (for the custom help formatter)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const schema = JSON.parse(fs.readFileSync(path.join(ROOT, 'config', 'parameter-schema-v2.json'), 'utf8'));
const outDir = path.join(ROOT, 'src', 'lib', 'generated');
fs.mkdirSync(outDir, { recursive: true });

// Map schema groups to help section names (must match existing help formatter output)
const GROUP_TO_SECTION = {
    'project': 'general',
    'model': 'model',
    'infrastructure': 'infra',
    'endpoint': 'endpoint',
    'inference-component': 'ic',
    'async': 'async',
    'batch': 'batch',
    'hyperpod': 'hyperpod',
    'lora': 'features',
    'benchmark': 'general',
    'auth': 'auth',
    'build': 'infra',
    'testing': 'features'
};

const options = [];
const helpGroups = {};

for (const [key, param] of Object.entries(schema.parameters)) {
    if (!param.cliFlag) continue;

    const flag = param.cliArgName
        ? `${param.cliFlag} <${param.cliArgName}>`
        : param.cliFlag;

    const entry = { flag, description: param.description };

    if (param.validation?.enum) entry.choices = param.validation.enum;
    if (param.deprecated) entry.hidden = true;
    if (param.repeatable) entry.repeatable = true;
    if (param.default !== null && param.default !== undefined && !param.repeatable) {
        entry.defaultValue = param.default;
    }

    options.push(entry);

    // Help group mapping
    const section = GROUP_TO_SECTION[param.group] || 'general';
    // Special cases to match existing formatter
    if (['--smart', '--discover'].includes(param.cliFlag)) {
        helpGroups[param.cliFlag] = 'mcp';
    } else if (['--no-validate', '--validate-env-vars', '--validate-with-docker', '--offline'].includes(param.cliFlag)) {
        helpGroups[param.cliFlag] = 'validation';
    } else if (['--model-env', '--server-env'].includes(param.cliFlag)) {
        helpGroups[param.cliFlag] = 'env';
    } else {
        helpGroups[param.cliFlag] = section;
    }
}

const output = `// AUTO-GENERATED by scripts/codegen-cli.js — DO NOT EDIT
// Source: config/parameter-schema-v2.json
// Generated: ${new Date().toISOString()}

/**
 * CLI option definitions derived from parameter-schema-v2.json.
 * Each entry can be registered with Commander via:
 *   new Option(entry.flag, entry.description)
 */
export const cliOptions = ${JSON.stringify(options, null, 4)};

/**
 * Maps CLI flags to help section groups.
 * Used by the custom help formatter in bin/cli.js.
 */
export const helpGroups = ${JSON.stringify(helpGroups, null, 4)};
`;

fs.writeFileSync(path.join(outDir, 'cli-options.js'), output);
console.log(`✅ Generated src/lib/generated/cli-options.js (${options.length} options, ${Object.keys(helpGroups).length} help mappings)`);
